# Generated by Django 5.2 on 2025-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.IntegerField(default=0)),
                ('quantity', models.CharField(choices=[('1kg', '1 kg'), ('500g', '500 g'), ('1pc', '1 piece')], default='1kg', max_length=10)),
            ],
        ),
    ]
